name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  ci:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - 8.6.5
          - 8.8.4
          - 8.10.2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: 3.2.0.0
      - run: cabal build
      - run: cabal test --test-show-details=direct
      - run: cabal haddock
      - run: cabal sdist
  ormolu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check formatting
        run: |
          ORMOLU=$(mktemp -t)
          wget -O $ORMOLU https://github.com/tweag/ormolu/releases/download/0.1.3.0/ormolu-Linux
          chmod +x $ORMOLU
          $ORMOLU -o-X{TypeApplications,PatternSynonyms,BangPatterns} -i $(find src test doctest -name '*.hs' -type f)
          git status --porcelain
          [[ $(git status --porcelain | wc -l) -eq 0 ]]
