name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  ci:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - 8.6.5
          - 8.8.4
          - 8.10.2
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: 3.2.0.0
      - run: cabal build
      - run: cabal test --test-show-details=direct
      - run: cabal haddock
      - run: cabal check
      - run: cabal sdist
  ormolu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mrkkrp/ormolu-action@v1
        with:
          extra-args: -o-XTypeApplications -o-XPatternSynonyms -o-XBangPatterns
