name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/run-ormolu@v16
      - uses: tfausak/cabal-gild-setup-action@v2
        with:
          version: 1.5.0.1
      - name: Run cabal-gild
        run: |
          find . -name '*.cabal' -type f -exec cabal-gild --io={} \;
  ci:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - 8.6.5
          - 8.8.4
          - 8.10.7
          - 9.0.2
          - 9.2.8
          - 9.4.8
          - 9.6.6
          - 9.8.4
          - 9.10.1
          - 9.12.1
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}
      - name: Setup cabal-docspec
        run: |
          CABAL_DIR=~/.cabal/bin
          echo "$CABAL_DIR" >> $GITHUB_PATH
          DOCSPEC="$CABAL_DIR/cabal-docspec"
          mkdir -p "$CABAL_DIR"
          curl -sL https://github.com/phadej/cabal-extras/releases/download/cabal-docspec-$CABAL_DOCSPEC_VERSION/cabal-docspec-$CABAL_DOCSPEC_VERSION-x86_64-linux.xz | xz -d > "$DOCSPEC"
          chmod +x "$DOCSPEC"
          "$DOCSPEC" --version
        env:
          CABAL_DOCSPEC_VERSION: "0.0.0.20240703"

      - name: Configure
        run: cabal configure --enable-tests
      - name: Freeze build
        run: cabal freeze
      - uses: actions/cache@v4
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: cabal-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            cabal-${{ matrix.ghc }}

      - name: Build dependencies
        run: cabal build --only-dependencies
      - name: Build
        run: cabal build
      - name: Run tests
        run: cabal test --test-show-details=direct
      - name: Run docspec
        run: cabal-docspec
      - run: cabal check
